### ISSUE TITLE
Bug - GIF Frame-rate

### ISSUE THREAD

**Issue by tommyboylab** [dehlen/Capture#55]
First want to say I'm really excited for this application. I've tried the other ones in the readme and even a paid one (GfFox) and I can say I like the design and UX of this much more than any of those apps. 

Unfortunately I've been encountering an issue with capture I haven't been able to solve regarding the frame-rate of recorded Gifs, even after setting the frame rate in the application I'm finding the Gifs are LIGHTNING fast; I can barely see what I'm trying to show. I'm not sure if it's because of the default frame-rate that was set in V1.0 or if it's something on my side, but I thought I'd reach out and see if anyone else has had something similar/ knows how to fix it. 

Here's an example and thanks again for the development of this app. 👍 

![ScreenRecording 2019-03-13 14 42 38-trimmed](https://user-images.githubusercontent.com/44362297/55325458-7281bf00-5485-11e9-91b7-3d3f6124b409.gif)

**Comment by dehlen** [comment]
First of all thanks for getting in touch. This is a known issue and was already fixed. I mistakenly set the frameCount instead of the frames per seconds. Therefore your resulting gif only has f.e 30 frames instead of 30 frames per second which makes the GIF lightning fast. The current master branch already includes the bug fix along with a lot of new added features. I added sandbox support, selecting a custom crop frame and made multiple other adjustments. Since i am currently working on a new "trailer" for v2.0 of the app I did not release a new version yet. However once I get my hands on updating the trailer video at https://captureapp.dev I'll release 2.0. If you want to get your hands on the new version before that I'll recommend building your own version with Xcode. However I am planning to release the new version in at least the next 2 weeks.

I'll wait to close the issue for a few days so you have the chance to get back to me if your issue still persists. Feel free to close however if your issue was addressed.

**Comment by tommyboylab** [comment]
I tried building the application from source, when running it I was unable to get the video editor open to test if the issue was fixed, I'll wait for your V2.0 and report the issue if it appears then. Closing ticket for now.

**Comment by dehlen** [comment]
Hey @tommyboylab I pre-released 2.0.0 for you to check. It is available via the Releases Tab at https://github.com/dehlen/Capture/releases. I think automatically updating via the 1.0.0 will not work with this pre-release version so feel free to download the zip and try for yourself. I hope this fixes your issue.

**Comment by tommyboylab** [comment]
Came back to say 2.0.1 is working great. Really improves my workflow and I really appreciate you pre-releasing it for me.
